### ISSUE TITLE
Readthedocs is not picking up releases

### ISSUE THREAD

**Issue by lb-** [wagtail/sphinx-wagtail-theme#226]
It would be also good to work out why releases are not showing as expected in the release picker in the built docs. 

https://readthedocs.org/projects/sphinx-wagtail-theme/

It is only showing versions;

* latest
* v5.0.0.a0
* v4.1.0
* v3.2.0

### Screenshot

![Screenshot_20221015-161551](https://user-images.githubusercontent.com/1396140/195972411-7c29c6f3-8591-483c-912d-c3dfbb093d9c.png)

**Comment by lb-** [comment]
Updated this issue to be only focused on the docs version issues, could not see a quick fix by searching through code.

My guess is that something needs to be added to our release process https://github.com/wagtail/sphinx_wagtail_theme#release-process

**Comment by Temidayo32** [comment]
@lb- I will like to look into this issue

**Comment by lb-** [comment]
Go for it. I don't really know where to start on this sorry as I'm not super familiar with how RTD works. My concern is that this may require a log-in to the project's RTD account. Any research would be appreciated.

**Comment by Temidayo32** [comment]
okay, will do, and inform you on how it goes

**Comment by Temidayo32** [comment]
@lb- see the Wagtail documentation itself is showing all releases!
![Screenshot (132)](https://user-images.githubusercontent.com/87539866/196654303-51e7c7f9-558d-4d12-9fc4-95e6ccf07d2d.png)

**Comment by Temidayo32** [comment]
See some info I found.

_"Once you have tags/branches created on your Git project, you have to "Activate those versions" on Read the Docs to be built. Go to your Read the Docs' project page and click on "Versions". From there, select the version you want to activate and then save it. After that, it will be built and hosted on Read the Docs."_

So I think it is an RTD thing. Perhaps, those versions are not activated in RTD. Versions is settings in RTD

**Comment by thibaudcolas** [comment]
I have added an [automation rule](https://docs.readthedocs.io/en/stable/automation-rules.html) in Read the Docs so all tags activate as versions when pushed and can confirm this worked as expected for `6.0.0`. However I don’t think this will be that useful for us. Since the theme’s static files are defined in Sass, Read the Docs can’t build the project from source. This is why the `latest` version of the theme in RTD is built from the project’s `gh-pages` rather than the main branch.

So – perhaps it might be better for us to only have `latest` configured to build there?

**Comment by thibaudcolas** [comment]
My point above about front-end tooling is no longer true, as Read the Docs now supports Docker-style installation scripts.

And the automation rule is working as expected. So I believe this is all sorted.
