### ISSUE TITLE
The version button is not closing after opening it on the documentation page(Getting Started/Your first wagtail site)

### ISSUE THREAD

**Issue by MJCoder15** [wagtail/sphinx-wagtail-theme#247]
### Issue Summary

On getting_started/tutorial.html on the bottom right  we have a "versions" button, and the problem is if we click on it, then it normally opens but there is no close button for It

### Steps to Reproduce

1. Search wagtail on browser
2. Open  wagtail's official site `https://wagtail.org/`, and click on **get started** button
3. And then click on **Build Your First Site**
4. On the bottom right corner we can see a button for different versions
![image](https://user-images.githubusercontent.com/91000828/218749099-6b520ffc-8927-4c6d-8633-04cf536bbc66.png)

5. Click on It and  It normally opens but there is no way of closing it, until we refresh the site.

### Video version of problem

https://user-images.githubusercontent.com/91000828/218751798-bab9b96a-5492-4b38-a4c0-2be962e4a29c.mp4

**Comment by laymonage** [comment]
The fix is already here:

https://github.com/wagtail/sphinx_wagtail_theme/blob/5a42098f0c75843b0f7aab922b9c69994dbf4768/sass/_component_versionpicker_fix.scss#L11

but it loses to the specificity of the default `.rst-versions.shift-up` rule:

<img width="382" alt="image" src="https://user-images.githubusercontent.com/6379424/218760060-937ab0f0-b07a-4649-b6ed-1cf024df7071.png">


Adding the `.shift-up` selector should fix it.

**Comment by MJCoder15** [comment]
I am currently going through development instructions to set up local environment so before I do anything ahead can you assign me this issue plaese.

**Comment by lb-** [comment]
@MJCoder15 we don't assign issues - just go ahead and give it a go when you're ready.

**Comment by MJCoder15** [comment]
OK Got It👍🏽

**Comment by lb-** [comment]
PR up https://github.com/wagtail/sphinx-wagtail-theme/pull/261
