### ISSUE TITLE
"No module named 'pkg_resources'" error when installing against Python 3.12

### ISSUE THREAD

**Issue by gasman** [wagtail/sphinx-wagtail-theme#272]
On a fairly new* Python 3.12 virtualenv, running the following from the root of the Wagtail codebase

```
pip install -e .[docs]
cd docs
make html
```

results in the error:

```
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v5.3.0

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Users/matthew/.virtualenvs/wagtailpy312/lib/python3.12/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/docs/conf.py", line 19, in <module>
    import sphinx_wagtail_theme
  File "/Users/matthew/.virtualenvs/wagtailpy312/lib/python3.12/site-packages/sphinx_wagtail_theme/__init__.py", line 4, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

make: *** [html] Error 2
```

This is with Python 3.12.0, pip 23.2.1.

\* created about a week ago - haven't tried replicating this from scratch yet

**Comment by thibaudcolas** [comment]
Ran into this too :)

I assume this is because `setuptools` is no longer installed by default. According to the [`pkg_resources` docs](https://setuptools.pypa.io/en/latest/pkg_resources.html), that module is now deprecated. Looks like we could replace it with [importlib.metadata](https://docs.python.org/3.11/library/importlib.metadata.html#module-importlib.metadata), introduced in Python 3.7:

```python
from importlib.metadata import version  
version("sphinx_wagtail_theme")  
```

Or hard-code the version number, it’s not like this package is updated often.

**Comment by kituuu** [comment]
Hey, can I work on this? @thibaudcolas

**Comment by thibaudcolas** [comment]
Yes, go for it.

**Comment by kituuu** [comment]
Hey, do we have to follow the setup instructions (given in README) before running these command. Because without that I am getting this...
<img width="1472" alt="image" src="https://github.com/wagtail/sphinx-wagtail-theme/assets/66073214/3b46c06a-a9ef-4042-962d-1e25f18bdb78">
macOS - Sonoma 
virtenv - python 3.12.1
@thibaudcolas

**Comment by gasman** [comment]
@kituuu See https://docs.wagtail.org/en/stable/contributing/developing.html#compiling-the-documentation - there's an alternative command to run here if you're using zsh.

**Comment by kituuu** [comment]
Thanks @gasman

**Comment by kituuu** [comment]
Hmm, any idea if this error is OS specific or not? Because for me it is working fine.
<img width="1728" alt="image" src="https://github.com/wagtail/sphinx-wagtail-theme/assets/66073214/d64e4c98-f397-4bec-a3b4-6473ffcf84c4">

first installed pyenv -> installed python 3.12.0 -> set it as my global python version
ran pipenv install to make a virtual environment in the root folder
then pipenv shell to activate the environment.

**Comment by thibaudcolas** [comment]
@kituuu interesting! Could you try with a vanilla virtual environment rather than `pipenv` perhaps? Also I don’t expect this would make a difference but just in case, the command that caused this for me is `make spelling` / `sphinx-build -b spelling -d _build/doctrees   . _build/spelling`.

After you’ve created your virtual environment (or with your current `pipenv` one), you can share the output of `pip list` or equivalent with us so we can double check whether `setuptools` is there or not.

**Comment by kituuu** [comment]
@thibaudcolas  Pip list has setuptools in it.
<img width="1082" alt="image" src="https://github.com/wagtail/sphinx-wagtail-theme/assets/66073214/eaa95db1-7e84-4af3-a5de-765aed028858">
pip list has setuptools in it. I tried creating a virtual env with conda instead of pipenv, but again, setuptools will install. 

Ig with standard venv setup, we don't have setup tools
<img width="1365" alt="image" src="https://github.com/wagtail/sphinx-wagtail-theme/assets/66073214/83915295-80fb-4ab9-830d-acca724be401">
I can reproduce the error, now. 
Working on the fix : D
